import bitcoin from "assets/icons/main/bitcoin.png";
import chart from "assets/icons/main/chart.svg";

export const TYPES = [
  { id: 0, title: "All", koreanTitle: "모두" },
  { id: 1, title: "Crypto", koreanTitle: "가상자산" },
  { id: 2, title: "Stock", koreanTitle: "주식" },
  { id: 3, title: "Index", koreanTitle: "지수" },
];

export const RISKS = [
  { id: 0, title: "All", koreanTitle: "모두" },
  { id: 1, title: "Very high", koreanTitle: "매우 위험" },
  { id: 2, title: "High", koreanTitle: "위험" },
  { id: 3, title: "Moderate", koreanTitle: "적정" },
  { id: 4, title: "Low", koreanTitle: "안전" },
];

export const WEATHERS = [
  { id: 0, title: "All", koreanTitle: "모두" },
  { id: 1, title: "Sunny", koreanTitle: "맑음" },
  { id: 2, title: "Partly_cloudy", koreanTitle: "약간 흐림" },
  { id: 3, title: "Mostly_cloudy", koreanTitle: "흐림" },
  { id: 4, title: "Rainy", koreanTitle: "비" },
  { id: 5, title: "Thunderstorm", koreanTitle: "천둥번개" },
  { id: 6, title: "Hurricane", koreanTitle: "태풍" },
  { id: 7, title: "Volcano", koreanTitle: "화산폭발" },
];

export const LOCATIONS = [
  { id: 0, title: "All", koreanTitle: "모두" },
  { id: 1, title: "United States", koreanTitle: "미국" },
  { id: 2, title: "Taiwan", koreanTitle: "대만" },
  { id: 3, title: "Switzerland", koreanTitle: "스위스" },
  { id: 4, title: "China", koreanTitle: "중국" },
  { id: 5, title: "Netherlands", koreanTitle: "네덜란드" },
  { id: 6, title: "Korea (South)", koreanTitle: "대한민국" },
  { id: 7, title: "United Kingdom", koreanTitle: "영국" },
  { id: 8, title: "France", koreanTitle: "프랑스" },
  { id: 9, title: "Australia", koreanTitle: "호주" },
  { id: 10, title: "Japan", koreanTitle: "일본" },
  { id: 11, title: "Hongkong", koreanTitle: "홍콩" },
  { id: 12, title: "Canada", koreanTitle: "캐나다" },
  { id: 13, title: "Germany", koreanTitle: "독일" },
  { id: 14, title: "India", koreanTitle: "인도" },
  { id: 15, title: "Spain", koreanTitle: "스페인" },
  { id: 16, title: "Brazil", koreanTitle: "브라질" },
  { id: 17, title: "Belgium", koreanTitle: "벨기에" },
  { id: 18, title: "Italy", koreanTitle: "이탈리아" },
  { id: 19, title: "Sweden", koreanTitle: "스웨덴" },
  { id: 20, title: "Norway", koreanTitle: "노르웨이" },
  { id: 21, title: "Saudi Arabia", koreanTitle: "사우디 아라비아" },
  { id: 22, title: "South Africa", koreanTitle: "남아프리카 공화국" },
  { id: 23, title: "Ireland", koreanTitle: "아일랜드" },
  { id: 24, title: "Mexico", koreanTitle: "멕시코" },
  { id: 25, title: "Finland", koreanTitle: "핀란드" },
  { id: 26, title: "Indonesia", koreanTitle: "인도네시아" },
  { id: 27, title: "Singapore", koreanTitle: "싱가폴" },
  { id: 28, title: "Qatar", koreanTitle: "카타르" },
  { id: 29, title: "Kuwait", koreanTitle: "쿠웨이트" },
  { id: 30, title: "United Arab Emirates", koreanTitle: "아랍 에미리트" },
  { id: 31, title: "Denmark", koreanTitle: "덴마크" },
  { id: 32, title: "Israel", koreanTitle: "이스라엘" },
  { id: 33, title: "Austria", koreanTitle: "오스트리아" },
  { id: 34, title: "New Zealand", koreanTitle: "뉴질랜드" },
  { id: 35, title: "Peru", koreanTitle: "페루" },
  { id: 36, title: "Philippines", koreanTitle: "필리핀" },
  { id: 37, title: "Poland", koreanTitle: "폴란드" },
  { id: 38, title: "Hungary", koreanTitle: "헝가리" },
  { id: 39, title: "Colombia", koreanTitle: "콜롬비아" },
  { id: 40, title: "Chile", koreanTitle: "칠레" },
  { id: 41, title: "Greece", koreanTitle: "그리스" },
  { id: 42, title: "Russian Federation", koreanTitle: "러시아" },
  { id: 43, title: "Portugal", koreanTitle: "포르투갈" },
  { id: 44, title: "Czech Republic", koreanTitle: "체코" },
  { id: 45, title: "Thailand", koreanTitle: "태국" },
  { id: 46, title: "Hong Kong", koreanTitle: "홍콩" },
  { id: 47, title: "Turkey", koreanTitle: "튀르키예" },
  { id: 48, title: "Philippine", koreanTitle: "필리핀" },
];

export const EXCHAGNES = [
  { id: 0, title: "All", koreanTitle: "모두" },
  { id: 5, title: "NASDAQ", koreanTitle: "나스닥" },
  { id: 6, title: "Russell 2000", koreanTitle: "러셀 2000" },
  { id: 7, title: "NYSE COMPOSITE", koreanTitle: "NYSE COMPOSITE" },
  { id: 8, title: "KOSPI", koreanTitle: "코스피" },
  { id: 9, title: "S&P/TSX Composite", koreanTitle: "S&P/TSX Composite" },
  { id: 10, title: "FTSE 100", koreanTitle: "FTSE 100" },
  { id: 11, title: "Nikkei 225", koreanTitle: "니케이 225" },
  { id: 12, title: "DAX", koreanTitle: "DAX" },
  { id: 13, title: "Hangseng", koreanTitle: "항셍지수" },
  { id: 14, title: "NIFTY 50", koreanTitle: "NIFTY 50" },
  { id: 15, title: "IBEX 35", koreanTitle: "IBEX 35" },
  { id: 16, title: "IBOVESPA", koreanTitle: "IBOVESPA" },
  { id: 17, title: "AEX", koreanTitle: "AEX" },
  { id: 18, title: "BEL 20", koreanTitle: "BEL 20" },
  { id: 19, title: "FTSE MIB", koreanTitle: "FTSE MIB" },
  { id: 20, title: "OMX Nordic 40", koreanTitle: "OMX Nordic 40" },
  { id: 21, title: "Oslo Bors Benchmark", koreanTitle: "Oslo Bors Benchmark" },
  { id: 22, title: "JSE Limited", koreanTitle: "JSE Limited" },
  { id: 23, title: "ISEQ All Share", koreanTitle: "ISEQ All Share" },
  { id: 24, title: "Bolsa Mexicana De Valores", koreanTitle: "Bolsa Mexicana De Valores" },
  { id: 25, title: "OMX Helsinki 25", koreanTitle: "OMX Helsinki 25" },
  { id: 26, title: "IDX COMPOSITE", koreanTitle: "IDX COMPOSITE" },
  { id: 27, title: "Singapore Exchange Ltd", koreanTitle: "Singapore Exchange Ltd" },
  { id: 28, title: "Abu Dhabi Securities Exchange", koreanTitle: "Abu Dhabi Securities Exchange" },
  { id: 29, title: "OMX Copenhagen", koreanTitle: "OMX Copenhagen" },
  { id: 30, title: "CBOE Volatility Index", koreanTitle: "CBOE Volatility Index" },
  { id: 31, title: "Austrian Traded Index", koreanTitle: "Austrian Traded Index" },
  { id: 32, title: "S&P/NZX 50", koreanTitle: "S&P/NZX 50" },
  { id: 33, title: "PSEI", koreanTitle: "PSEI" },
  { id: 34, title: "WIG20", koreanTitle: "WIG20" },
  { id: 35, title: "Budapest Stock Exchange", koreanTitle: "Budapest Stock Exchange" },
  { id: 36, title: "KLCI", koreanTitle: "KLCI" },
  { id: 37, title: "TSEC weighted index", koreanTitle: "TSEC weighted index" },
  { id: 38, title: "Bolsa de Valores de Colombia", koreanTitle: "Bolsa de Valores de Colombia" },
  { id: 39, title: "S&P IPSA", koreanTitle: "S&P IPSA" },
  { id: 40, title: "Hellenic Exchanges", koreanTitle: "Hellenic Exchanges" },
  { id: 41, title: "MOEX", koreanTitle: "MOEX" },
  { id: 42, title: "Tadawul All Shares", koreanTitle: "Tadawul All Shares" },
  { id: 43, title: "Qatar Exchange", koreanTitle: "Qatar Exchange" },
  { id: 44, title: "Kuwait Stock Exchange", koreanTitle: "Kuwait Stock Exchange" },
  { id: 45, title: "Tel Aviv Stock Exchange Ltd.", koreanTitle: "Tel Aviv Stock Exchange Ltd." },
  { id: 46, title: "DFM General", koreanTitle: "DFM General" },
  { id: 47, title: "TSEC", koreanTitle: "TSEC" },
  { id: 48, title: "Euronext N.V.", koreanTitle: "Euronext N.V." },
  { id: 49, title: "S&P/ASX 200", koreanTitle: "S&P/ASX 200" },
];

export const SECTROS = [
  { id: 0, title: "All", koreanTitle: "모두" },
  { id: 1, title: "Information Technology", koreanTitle: "정보 기술" },
  { id: 2, title: "Consumer Discretionary", koreanTitle: "임의 소비재" },
  { id: 3, title: "Communication", koreanTitle: "통신" },
  { id: 4, title: "Health Care", koreanTitle: "헬스케어" },
  { id: 5, title: "Energy", koreanTitle: "에너지" },
  { id: 6, title: "Consumer Staples", koreanTitle: "필수 소비재" },
  { id: 7, title: "Materials", koreanTitle: "재료" },
  { id: 8, title: "Utilities", koreanTitle: "유틸리티" },
  { id: 9, title: "Industrials", koreanTitle: "산업재" },
  { id: 10, title: "Real Estate", koreanTitle: "부동산" },
];

export const VIEWS = [
  { id: 0, title: 20, koreanTitle: 20 },
  { id: 1, title: 50, koreanTitle: 50 },
  { id: 2, title: 100, koreanTitle: 100 },
];

export const CURRENCIES = [
  { id: 0, title: 'KRW', koreanTitle: '원(￦)' },
  { id: 1, title: 'USD', koreanTitle: '달러(＄)' },
]

export const EXPLORES = [
  {
    id: 0,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 50,
    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 1,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,
    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 2,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 70.5,
    chartImage: chart,
    weatherIcon: "maintaining",
    weather: "Maintaining",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 3,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 80.8,
    chartImage: chart,
    weatherIcon: "slightlyRising",
    weather: "Slightly Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 4,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 60,
    chartImage: chart,
    weatherIcon: "sharplyRising",
    weather: "Sharply Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 5,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 90.1,
    chartImage: chart,
    weatherIcon: "extremelyRising",
    weather: "Extremely Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 6,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 79.2,
    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 7,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 90.6,
    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 8,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 48.3,
    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 9,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 50,
    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 10,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,
    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 11,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,
    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 12,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 70.5,
    chartImage: chart,
    weatherIcon: "maintaining",
    weather: "Maintaining",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 13,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 80.8,
    chartImage: chart,
    weatherIcon: "slightlyRising",
    weather: "Slightly Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 14,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 60,
    chartImage: chart,
    weatherIcon: "sharplyRising",
    weather: "Sharply Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 15,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 90.1,

    chartImage: chart,
    weatherIcon: "extremelyRising",
    weather: "Extremely Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 16,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 79.2,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 17,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 90.6,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 18,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 48.3,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 0,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 50,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 1,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 2,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 70.5,

    chartImage: chart,
    weatherIcon: "maintaining",
    weather: "Maintaining",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 3,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 80.8,

    chartImage: chart,
    weatherIcon: "slightlyRising",
    weather: "Slightly Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 4,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 60,

    chartImage: chart,
    weatherIcon: "sharplyRising",
    weather: "Sharply Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 5,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 90.1,

    chartImage: chart,
    weatherIcon: "extremelyRising",
    weather: "Extremely Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 6,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 79.2,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 7,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 90.6,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 8,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 48.3,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 9,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 50,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 10,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 11,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 12,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 70.5,

    chartImage: chart,
    weatherIcon: "maintaining",
    weather: "Maintaining",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 13,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 80.8,

    chartImage: chart,
    weatherIcon: "slightlyRising",
    weather: "Slightly Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 14,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 60,

    chartImage: chart,
    weatherIcon: "sharplyRising",
    weather: "Sharply Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 15,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 90.1,

    chartImage: chart,
    weatherIcon: "extremelyRising",
    weather: "Extremely Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 16,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 79.2,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 17,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 90.6,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 18,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 48.3,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 0,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 50,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 1,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 2,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 70.5,

    chartImage: chart,
    weatherIcon: "maintaining",
    weather: "Maintaining",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 3,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 80.8,

    chartImage: chart,
    weatherIcon: "slightlyRising",
    weather: "Slightly Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 4,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 60,

    chartImage: chart,
    weatherIcon: "sharplyRising",
    weather: "Sharply Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 5,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 90.1,

    chartImage: chart,
    weatherIcon: "extremelyRising",
    weather: "Extremely Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 6,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 79.2,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 7,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 90.6,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 8,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 48.3,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 9,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 50,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 10,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 11,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 12,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 70.5,

    chartImage: chart,
    weatherIcon: "maintaining",
    weather: "Maintaining",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 13,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 80.8,

    chartImage: chart,
    weatherIcon: "slightlyRising",
    weather: "Slightly Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 14,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 60,

    chartImage: chart,
    weatherIcon: "sharplyRising",
    weather: "Sharply Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 15,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 90.1,

    chartImage: chart,
    weatherIcon: "extremelyRising",
    weather: "Extremely Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 16,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 79.2,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 17,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 90.6,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 18,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 48.3,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 0,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 50,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 1,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 2,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 70.5,

    chartImage: chart,
    weatherIcon: "maintaining",
    weather: "Maintaining",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 3,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 80.8,

    chartImage: chart,
    weatherIcon: "slightlyRising",
    weather: "Slightly Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 4,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 60,

    chartImage: chart,
    weatherIcon: "sharplyRising",
    weather: "Sharply Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 5,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 90.1,

    chartImage: chart,
    weatherIcon: "extremelyRising",
    weather: "Extremely Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 6,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 79.2,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 7,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 90.6,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 8,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 48.3,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 9,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 50,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 10,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 11,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 12,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 70.5,

    chartImage: chart,
    weatherIcon: "maintaining",
    weather: "Maintaining",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 13,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 80.8,

    chartImage: chart,
    weatherIcon: "slightlyRising",
    weather: "Slightly Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 14,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 60,

    chartImage: chart,
    weatherIcon: "sharplyRising",
    weather: "Sharply Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 15,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 90.1,

    chartImage: chart,
    weatherIcon: "extremelyRising",
    weather: "Extremely Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 16,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 79.2,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 17,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 90.6,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 18,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 48.3,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 0,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 50,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 1,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 2,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 70.5,

    chartImage: chart,
    weatherIcon: "maintaining",
    weather: "Maintaining",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 3,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 80.8,

    chartImage: chart,
    weatherIcon: "slightlyRising",
    weather: "Slightly Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 4,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 60,

    chartImage: chart,
    weatherIcon: "sharplyRising",
    weather: "Sharply Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 5,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 90.1,

    chartImage: chart,
    weatherIcon: "extremelyRising",
    weather: "Extremely Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 6,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 79.2,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 7,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 90.6,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 8,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 48.3,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 9,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 50,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 10,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 11,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 12,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 70.5,

    chartImage: chart,
    weatherIcon: "maintaining",
    weather: "Maintaining",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 13,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 80.8,

    chartImage: chart,
    weatherIcon: "slightlyRising",
    weather: "Slightly Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 14,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 60,

    chartImage: chart,
    weatherIcon: "sharplyRising",
    weather: "Sharply Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 15,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 90.1,

    chartImage: chart,
    weatherIcon: "extremelyRising",
    weather: "Extremely Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 16,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 79.2,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 17,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 90.6,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 18,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 48.3,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 0,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 50,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 1,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 2,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 70.5,

    chartImage: chart,
    weatherIcon: "maintaining",
    weather: "Maintaining",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 3,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 80.8,

    chartImage: chart,
    weatherIcon: "slightlyRising",
    weather: "Slightly Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 4,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 60,

    chartImage: chart,
    weatherIcon: "sharplyRising",
    weather: "Sharply Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 5,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 90.1,

    chartImage: chart,
    weatherIcon: "extremelyRising",
    weather: "Extremely Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 6,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 79.2,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 7,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 90.6,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 8,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 48.3,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 9,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 50,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 10,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 11,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 12,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 70.5,

    chartImage: chart,
    weatherIcon: "maintaining",
    weather: "Maintaining",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 13,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 80.8,

    chartImage: chart,
    weatherIcon: "slightlyRising",
    weather: "Slightly Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 14,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 60,

    chartImage: chart,
    weatherIcon: "sharplyRising",
    weather: "Sharply Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 15,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 90.1,

    chartImage: chart,
    weatherIcon: "extremelyRising",
    weather: "Extremely Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 16,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 79.2,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 17,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 90.6,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 18,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 48.3,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 0,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 50,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 1,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 2,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 70.5,

    chartImage: chart,
    weatherIcon: "maintaining",
    weather: "Maintaining",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 3,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 80.8,

    chartImage: chart,
    weatherIcon: "slightlyRising",
    weather: "Slightly Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 4,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 60,

    chartImage: chart,
    weatherIcon: "sharplyRising",
    weather: "Sharply Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 5,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 90.1,

    chartImage: chart,
    weatherIcon: "extremelyRising",
    weather: "Extremely Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 6,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 79.2,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 7,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 90.6,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 8,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 48.3,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 9,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 50,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 10,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 11,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 12,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 70.5,

    chartImage: chart,
    weatherIcon: "maintaining",
    weather: "Maintaining",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 13,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 80.8,

    chartImage: chart,
    weatherIcon: "slightlyRising",
    weather: "Slightly Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 14,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 60,

    chartImage: chart,
    weatherIcon: "sharplyRising",
    weather: "Sharply Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 15,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 90.1,

    chartImage: chart,
    weatherIcon: "extremelyRising",
    weather: "Extremely Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 16,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 79.2,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 17,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 90.6,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 18,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 48.3,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 0,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 50,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 1,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 2,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 70.5,

    chartImage: chart,
    weatherIcon: "maintaining",
    weather: "Maintaining",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 3,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 80.8,

    chartImage: chart,
    weatherIcon: "slightlyRising",
    weather: "Slightly Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 4,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 60,

    chartImage: chart,
    weatherIcon: "sharplyRising",
    weather: "Sharply Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 5,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 90.1,

    chartImage: chart,
    weatherIcon: "extremelyRising",
    weather: "Extremely Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 6,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 79.2,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 7,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 90.6,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 8,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 48.3,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 9,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 50,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 10,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 11,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 12,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 70.5,

    chartImage: chart,
    weatherIcon: "maintaining",
    weather: "Maintaining",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 13,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 80.8,

    chartImage: chart,
    weatherIcon: "slightlyRising",
    weather: "Slightly Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 14,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 60,

    chartImage: chart,
    weatherIcon: "sharplyRising",
    weather: "Sharply Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 15,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 90.1,

    chartImage: chart,
    weatherIcon: "extremelyRising",
    weather: "Extremely Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 16,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 79.2,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 17,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 90.6,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 18,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 48.3,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 0,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 50,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 1,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 2,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 70.5,

    chartImage: chart,
    weatherIcon: "maintaining",
    weather: "Maintaining",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 3,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 80.8,

    chartImage: chart,
    weatherIcon: "slightlyRising",
    weather: "Slightly Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 4,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 60,

    chartImage: chart,
    weatherIcon: "sharplyRising",
    weather: "Sharply Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 5,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 90.1,

    chartImage: chart,
    weatherIcon: "extremelyRising",
    weather: "Extremely Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 6,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 79.2,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 7,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 90.6,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 8,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 48.3,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 9,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 50,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 10,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 11,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 12,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 70.5,

    chartImage: chart,
    weatherIcon: "maintaining",
    weather: "Maintaining",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 13,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 80.8,

    chartImage: chart,
    weatherIcon: "slightlyRising",
    weather: "Slightly Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 14,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 60,

    chartImage: chart,
    weatherIcon: "sharplyRising",
    weather: "Sharply Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 15,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 90.1,

    chartImage: chart,
    weatherIcon: "extremelyRising",
    weather: "Extremely Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 16,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 79.2,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 17,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 90.6,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 18,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 48.3,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 0,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 50,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 1,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 2,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 70.5,

    chartImage: chart,
    weatherIcon: "maintaining",
    weather: "Maintaining",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 3,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 80.8,

    chartImage: chart,
    weatherIcon: "slightlyRising",
    weather: "Slightly Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 4,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 60,

    chartImage: chart,
    weatherIcon: "sharplyRising",
    weather: "Sharply Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 5,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 90.1,

    chartImage: chart,
    weatherIcon: "extremelyRising",
    weather: "Extremely Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 6,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 79.2,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 7,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 90.6,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 8,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 48.3,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 9,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 50,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 10,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 11,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 12,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 70.5,

    chartImage: chart,
    weatherIcon: "maintaining",
    weather: "Maintaining",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 13,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 80.8,

    chartImage: chart,
    weatherIcon: "slightlyRising",
    weather: "Slightly Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 14,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 60,

    chartImage: chart,
    weatherIcon: "sharplyRising",
    weather: "Sharply Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 15,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 90.1,

    chartImage: chart,
    weatherIcon: "extremelyRising",
    weather: "Extremely Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 16,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 79.2,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 17,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 90.6,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 18,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 48.3,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 0,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 50,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 1,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 2,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 70.5,

    chartImage: chart,
    weatherIcon: "maintaining",
    weather: "Maintaining",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 3,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 80.8,

    chartImage: chart,
    weatherIcon: "slightlyRising",
    weather: "Slightly Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 4,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 60,

    chartImage: chart,
    weatherIcon: "sharplyRising",
    weather: "Sharply Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 5,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 90.1,

    chartImage: chart,
    weatherIcon: "extremelyRising",
    weather: "Extremely Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 6,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 79.2,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 7,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 90.6,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 8,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 48.3,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 9,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 50,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 10,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 11,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 12,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 70.5,

    chartImage: chart,
    weatherIcon: "maintaining",
    weather: "Maintaining",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 13,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 80.8,

    chartImage: chart,
    weatherIcon: "slightlyRising",
    weather: "Slightly Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 14,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 60,

    chartImage: chart,
    weatherIcon: "sharplyRising",
    weather: "Sharply Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 15,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 90.1,

    chartImage: chart,
    weatherIcon: "extremelyRising",
    weather: "Extremely Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 16,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 79.2,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 17,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 90.6,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 18,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 48.3,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
];
