import { Colors, Menus } from "types/main";
import bitcoin from "assets/icons/main/bitcoin.png";
import chart from "assets/icons/main/chart.svg";
import news from "assets/icons/main/news.png";

export const COLORS: Colors = {
  Low: "bg-[#E6F5F0] text-[#34BB7A]",
  Moderate: "bg-[#FEF5E6] text-[#F99F01]",
  High: "bg-[#FFE4D9] text-[#FF4D00]",
  VeryHigh: "bg-[#FAE8E8] text-[#DF1525]",
  Very_high: "bg-[#FAE8E8] text-[#DF1525]",
  'Very high': "bg-[#FAE8E8] text-[#DF1525]",
};

export const PORTCOLORS: any = {
  "Low volatility": "bg-[#E6F5F0] text-[#34BB7A]",
  "Moderate volatility": "bg-[#FEF5E6] text-[#F99F01]",
  "High volatility": "bg-[#FFE4D9] text-[#FF4D00]",
  "Very High volatility": "bg-[#FAE8E8] text-[#DF1525]"
}

export const MENUS: any = [
  {
    id: 0,
    title: "Crypto",
    koreanTitle: "가상자산",
    list: [
      {
        id: 0,
        image: bitcoin,
        name: "Bitcoin",
        subName: "BTC-USD",
        risk: "Low",
        maximumLoss: 60.5,
        weather: "Sharply Falling",
        price: 24300.2,
        weatherIcon: "sharplyFalling",
      },
      {
        id: 1,
        image: bitcoin,
        name: "Bitcoin",
        subName: "BTC-USD",
        risk: "Moderate",
        maximumLoss: 71.5,
        weather: "Slightly Rising",
        price: 23900.7,
        weatherIcon: "slightlyRising",
      },
      {
        id: 2,
        image: bitcoin,
        name: "Bitcoin",
        subName: "BTC-USD",
        risk: "High",
        maximumLoss: 80.5,
        weather: "Sharply Rising",
        price: 23000.0,
        weatherIcon: "sharplyRising",
      },
      {
        id: 3,
        image: bitcoin,
        name: "Bitcoin",
        subName: "BTC-USD",
        risk: "VeryHigh",
        maximumLoss: 83.5,
        weather: "Risk of Explosion",
        price: 22300.0,
        weatherIcon: "explosion",
      },
      {
        id: 4,
        image: bitcoin,
        name: "Bitcoin",
        subName: "BTC-USD",
        risk: "VeryHigh",
        maximumLoss: 83.5,
        weather: "Maintaining",
        price: 22300.0,
        weatherIcon: "maintaining",
      },
      {
        id: 5,
        image: bitcoin,
        name: "Bitcoin",
        subName: "BTC-USD",
        risk: "VeryHigh",
        maximumLoss: 83.5,
        weather: "Extremely Rising",
        price: 22300.0,
        weatherIcon: "extremelyRising",
      },
      {
        id: 6,
        image: bitcoin,
        name: "Bitcoin",
        subName: "BTC-USD",
        risk: "VeryHigh",
        maximumLoss: 83.5,
        weather: "Slightly Falling",
        price: 22300.0,
        weatherIcon: "slightlyFalling",
      },
    ],
  },
  {
    id: 1,
    title: "Korean Stock",
    koreanTitle: "국내주식",

    list: [
      {
        id: 7,
        image: bitcoin,
        name: "Bitcoin",
        subName: "BTC-USD",
        risk: "Low",
        maximumLoss: 60.5,
        weather: "Sharply Falling",
        price: 24300.2,
        weatherIcon: "sharplyFalling",
      },
      {
        id: 8,
        image: bitcoin,
        name: "Bitcoin",
        subName: "BTC-USD",
        risk: "Moderate",
        maximumLoss: 71.5,
        weather: "Slightly Rising",
        price: 23900.7,
        weatherIcon: "slightlyRising",
      },
      {
        id: 9,
        image: bitcoin,
        name: "Bitcoin",
        subName: "BTC-USD",
        risk: "High",
        maximumLoss: 80.5,
        weather: "Sharply Rising",
        price: 23000.0,
        weatherIcon: "sharplyRising",
      },
      {
        id: 10,
        image: bitcoin,
        name: "Bitcoin",
        subName: "BTC-USD",
        risk: "VeryHigh",
        maximumLoss: 83.5,
        weather: "Risk of Explosion",
        price: 22300.0,
        weatherIcon: "explosion",
      },
      {
        id: 11,
        image: bitcoin,
        name: "Bitcoin",
        subName: "BTC-USD",
        risk: "VeryHigh",
        maximumLoss: 83.5,
        weather: "Maintaining",
        price: 22300.0,
        weatherIcon: "maintaining",
      },
      {
        id: 12,
        image: bitcoin,
        name: "Bitcoin",
        subName: "BTC-USD",
        risk: "VeryHigh",
        maximumLoss: 83.5,
        weather: "Extremely Rising",
        price: 22300.0,
        weatherIcon: "extremelyRising",
      },
      {
        id: 13,
        image: bitcoin,
        name: "Bitcoin",
        subName: "BTC-USD",
        risk: "VeryHigh",
        maximumLoss: 83.5,
        weather: "Slightly Falling",
        price: 22300.0,
        weatherIcon: "slightlyFalling",
      },
    ],
  },
  {
    id: 2,
    title: "Stock",
    koreanTitle: "해외주식",
    list: [
      {
        id: 14,
        image: bitcoin,
        name: "Bitcoin",
        subName: "BTC-USD",
        risk: "Low",
        maximumLoss: 60.5,
        weather: "Sharply Falling",
        price: 24300.2,
        weatherIcon: "sharplyFalling",
      },
      {
        id: 15,
        image: bitcoin,
        name: "Bitcoin",
        subName: "BTC-USD",
        risk: "Moderate",
        maximumLoss: 71.5,
        weather: "Slightly Rising",
        price: 23900.7,
        weatherIcon: "slightlyRising",
      },
      {
        id: 16,
        image: bitcoin,
        name: "Bitcoin",
        subName: "BTC-USD",
        risk: "High",
        maximumLoss: 80.5,
        weather: "Sharply Rising",
        price: 23000.0,
        weatherIcon: "sharplyRising",
      },
      {
        id: 17,
        image: bitcoin,
        name: "Bitcoin",
        subName: "BTC-USD",
        risk: "VeryHigh",
        maximumLoss: 83.5,
        weather: "Risk of Explosion",
        price: 22300.0,
        weatherIcon: "explosion",
      },
      {
        id: 18,
        image: bitcoin,
        name: "Bitcoin",
        subName: "BTC-USD",
        risk: "VeryHigh",
        maximumLoss: 83.5,
        weather: "Maintaining",
        price: 22300.0,
        weatherIcon: "maintaining",
      },
      {
        id: 19,
        image: bitcoin,
        name: "Bitcoin",
        subName: "BTC-USD",
        risk: "VeryHigh",
        maximumLoss: 83.5,
        weather: "Extremely Rising",
        price: 22300.0,
        weatherIcon: "extremelyRising",
      },
      {
        id: 20,
        image: bitcoin,
        name: "Bitcoin",
        subName: "BTC-USD",
        risk: "VeryHigh",
        maximumLoss: 83.5,
        weather: "Slightly Falling",
        price: 22300.0,
        weatherIcon: "slightlyFalling",
      },
    ],
  },
  {
    id: 3,
    title: "Index",
    koreanTitle: "지수",

    list: [
      {
        id: 21,
        image: bitcoin,
        name: "Bitcoin",
        subName: "BTC-USD",
        risk: "Low",
        maximumLoss: 60.5,
        weather: "Sharply Falling",
        price: 24300.2,
        weatherIcon: "sharplyFalling",
      },
      {
        id: 22,
        image: bitcoin,
        name: "Bitcoin",
        subName: "BTC-USD",
        risk: "Moderate",
        maximumLoss: 71.5,
        weather: "Slightly Rising",
        price: 23900.7,
        weatherIcon: "slightlyRising",
      },
      {
        id: 23,
        image: bitcoin,
        name: "Bitcoin",
        subName: "BTC-USD",
        risk: "High",
        maximumLoss: 80.5,
        weather: "Sharply Rising",
        price: 23000.0,
        weatherIcon: "sharplyRising",
      },
      {
        id: 24,
        image: bitcoin,
        name: "Bitcoin",
        subName: "BTC-USD",
        risk: "VeryHigh",
        maximumLoss: 83.5,
        weather: "Risk of Explosion",
        price: 22300.0,
        weatherIcon: "explosion",
      },
      {
        id: 25,
        image: bitcoin,
        name: "Bitcoin",
        subName: "BTC-USD",
        risk: "VeryHigh",
        maximumLoss: 83.5,
        weather: "Maintaining",
        price: 22300.0,
        weatherIcon: "maintaining",
      },
      {
        id: 26,
        image: bitcoin,
        name: "Bitcoin",
        subName: "BTC-USD",
        risk: "VeryHigh",
        maximumLoss: 83.5,
        weather: "Extremely Rising",
        price: 22300.0,
        weatherIcon: "extremelyRising",
      },
      {
        id: 27,
        image: bitcoin,
        name: "Bitcoin",
        subName: "BTC-USD",
        risk: "VeryHigh",
        maximumLoss: 83.5,
        weather: "Slightly Falling",
        price: 22300.0,
        weatherIcon: "slightlyFalling",
      },
    ],
  },
];

export const RISKS = [
  { id: 0, country: "United States", coin: 2 },
  { id: 1, country: "Korea", coin: 211 },
  { id: 2, country: "Japan", coin: 2302 },
  { id: 3, country: "China", coin: 1232 },
  { id: 4, country: "Australia", coin: 662 },
  { id: 5, country: "Belgium", coin: 2352 },
  { id: 6, country: "Britain", coin: 1235722 },
  { id: 7, country: "Canada", coin: 1232 },
  { id: 8, country: "India", coin: 22 },
  { id: 9, country: "Germany", coin: 0 },
  { id: 10, country: "France", coin: 12 },
  { id: 11, country: "Egypt", coin: 112352 },
  { id: 12, country: "Mexico", coin: 1232 },
];

export const RISK_MENUS = [
  { id: 0, title: "Bitcoin" },
  { id: 1, title: "Ethereum" },
  { id: 2, title: "Stock" },
  { id: 3, title: "Index" },
];

export const TRENDING_MENUS = [
  { id: 0, title: "Crypto", mobileEngTitle: "Crypto", koreanTitle: "가상자산" },
  { id: 1, title: "Korea (South)", mobileEngTitle: "KR", koreanTitle: "한국" },
  { id: 2, title: "United States", mobileEngTitle: "US", koreanTitle: "미국" },
  { id: 3, title: "United Kingdom", mobileEngTitle: "UK", koreanTitle: "영국" },
  { id: 4, title: "Japan", mobileEngTitle: "JP", koreanTitle: "일본" },
  { id: 5, title: "China", mobileEngTitle: "CN", koreanTitle: "중국" },
];

export const TRENDING_LIST = [
  {
    id: 0,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 50,
    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
  },
  {
    id: 1,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,
    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
  },
  {
    id: 2,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 70.5,
    chartImage: chart,
    weatherIcon: "maintaining",
    weather: "Maintaining",
  },
  {
    id: 3,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 80.8,
    chartImage: chart,
    weatherIcon: "slightlyRising",
    weather: "Slightly Rising",
  },
  {
    id: 4,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 60,
    chartImage: chart,
    weatherIcon: "sharplyRising",
    weather: "Sharply Rising",
  },
  {
    id: 5,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 90.1,
    chartImage: chart,
    weatherIcon: "extremelyRising",
    weather: "Extremely Rising",
  },
  {
    id: 6,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 79.2,
    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
  },
  {
    id: 7,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 90.6,
    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
  },
  {
    id: 8,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 48.3,
    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
  },
  {
    id: 9,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 50,
    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
  },
  {
    id: 10,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,
    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
  },
  {
    id: 11,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,
    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
  },
  {
    id: 12,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 70.5,
    chartImage: chart,
    weatherIcon: "maintaining",
    weather: "Maintaining",
  },
  {
    id: 13,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 80.8,
    chartImage: chart,
    weatherIcon: "slightlyRising",
    weather: "Slightly Rising",
  },
  {
    id: 14,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 60,
    chartImage: chart,
    weatherIcon: "sharplyRising",
    weather: "Sharply Rising",
  },
  {
    id: 15,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 90.1,
    chartImage: chart,
    weatherIcon: "extremelyRising",
    weather: "Extremely Rising",
  },
  {
    id: 16,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 79.2,
    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
  },
  {
    id: 17,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 90.6,
    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
  },
  {
    id: 18,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 48.3,
    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
  },
];

export const RISK_LEVELS = [
  { id: 0, title: "Very high", koreanTitle: "매우 위험" },
  { id: 1, title: "High", koreanTitle: "위험" },
  { id: 2, title: "Moderate", koreanTitle: "적정" },
  { id: 3, title: "Low", koreanTitle: "안전" },
];

export const NEWS = [
  {
    id: 0,
    title:
      "[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 1,
    title:
      "[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 2,
    title:
      "[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 3,
    title:
      "[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 4,
    title:
      "[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 5,
    title:
      "2[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 6,
    title:
      "2[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 7,
    title:
      "2[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 8,
    title:
      "2[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 9,
    title:
      "2[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 10,
    title:
      "3[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 11,
    title:
      "3[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 12,
    title:
      "3[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 13,
    title:
      "3[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 14,
    title:
      "3[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 15,
    title:
      "4[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 16,
    title:
      "4[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 17,
    title:
      "4[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 18,
    title:
      "4[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 19,
    title:
      "4[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 20,
    title:
      "5[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 21,
    title:
      "5[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 22,
    title:
      "5[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 23,
    title:
      "5[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 24,
    title:
      "5[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 25,
    title:
      "6[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 26,
    title:
      "6[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 27,
    title:
      "6[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 28,
    title:
      "6[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 29,
    title:
      "6[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 30,
    title:
      "[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 31,
    title:
      "[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 32,
    title:
      "[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 33,
    title:
      "[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 34,
    title:
      "[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 35,
    title:
      "[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 36,
    title:
      "[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 37,
    title:
      "[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 38,
    title:
      "[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 39,
    title:
      "[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 40,
    title:
      "[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 41,
    title:
      "[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 42,
    title:
      "[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 43,
    title:
      "[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 44,
    title:
      "[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 45,
    title:
      "[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 46,
    title:
      "[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 47,
    title:
      "[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 48,
    title:
      "[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 49,
    title:
      "[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 50,
    title:
      "[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 11,
    title:
      "[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 51,
    title:
      "[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 52,
    title:
      "[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 53,
    title:
      "[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 54,
    title:
      "[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 55,
    title:
      "[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 56,
    title:
      "[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 57,
    title:
      "[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 58,
    title:
      "[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 59,
    title:
      "[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 60,
    title:
      "[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 61,
    title:
      "[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 62,
    title:
      "[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 63,
    title:
      "[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 64,
    title:
      "[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 65,
    title:
      "[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 66,
    title:
      "[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 67,
    title:
      "[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 68,
    title:
      "[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 69,
    title:
      "[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 70,
    title:
      "[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
  {
    id: 71,
    title:
      "[News] Elon Musk Reaffirms Offer to Eat Happy Meal on TV if McDonald's Accepts Dogecoin",
    subTitle: "McDonald's Accepts Dogecoin",
    date: "2023.01.05",
    image: news,
  },
];
